### ISSUE TITLE
Falta um tipo Sanguíneo!!

### ISSUE THREAD

**Issue by FernandoAz09** [FehSchiavon/ControleDeAcademia#28]
Fala @FehSchiavon, blz??

Sou estudante do bootcamp **LaunchBase** da Rocketseat tbm!!

Acabei travando em uma parte aqui do Controle de academia e GRAÇAS a você consegui **desBUGAR** meu código!!

mas observei que em seu código da parte de SHOW no members.js, falta o tipo sanguíneo **AB - (negativo)**.... como sou perfeccionista e pela tua identação e organização, acredito que também seja!! 

Pra facilitar é só dar um ctrl+c ctrl+v aee

const converterBlood = data.members.find(function(member) {
        if ('A1' == member.blood) {
            member.blood = 'A +'
        } else if ('A0' == member.blood) {
            member.blood = 'A -'
        } else if ('B1' == member.blood) {
            member.blood = 'B +'
        } else if ('B2' == member.blood) {
            member.blood = 'B -'
        } else if ('AB1' == member.blood) {
            member.blood = 'AB +'
        } else if ('AB0' == member.blood) {
                member.blood = 'AB -'
        } else if ('O1' == member.blood) {
            member.blood = 'O +'
        } else if ('O0' == member.blood) {
            member.blood = 'O -'
        } 
    })

VLW!!

**Comment by FehSchiavon** [comment]
Bom dia Irmão! @FernandoAz09 
Nossa não sabe como fico feliz que tenha ajudado. Porque nunca imaginei que poderia ajudar, ainda mais com tantos códigos espalhados para todos os lados. 

Ó se agradeço! Vou aplicar lá sim. Se quiser também dar um Pull requests. Eu depois dou um Merge nele na branch principal.
E outra coisa se quiser me chamar lá discord também #tmj @FehSchiavon

**Comment by FernandoAz09** [comment]
VISH manooo

aí já tá difícil pra mim kkkk

Vou ver se consigo entender como faz essa Pull request e depois eu tento....

Já adicionei lá no Discord!! Bom dia aee !
